### ISSUE TITLE
Modified code

### ISSUE THREAD

**Issue by alaskamike** [nmalkin/plot-likert#1]
I've modified the package to facilitate different scales (both size and verbiage), removing null values, and plotting from one (long) line of code.  

plot_likert: 
    - added a couple of functions:
        - likert_response: replaces source data scores with scores that match scales in scales.py.  This is to fix the issue of "strongly agree" vs. "totally agree" and so on that I see in my own data sets.
        - plot_likert: combines likert_response, likert_counts/percentages and plot_counts into one line of code.
    - added support for even scales.
    - added the ability to wrap the text on the Y axis.

scales.py:
    - added '_0' scales to deal with (remove) NA responses from a dataset.  scoresX_0 is used to prep the data and scoresX is used for plotting.

colors.py:
    - added color scales based on the R likert package, with the lowest color being a little darker than the likert package.

I put the package here: https://bitbucket.org/alaskamike/plot_likert/src/master/

Please let me know if this is useful.

Mike

**Comment by nmalkin** [comment]
Hi Mike, this is awesome! These look like great improvements!

I'd be happy to incorporate your changes into this repo or, if you prefer, I can just link to yours — let me know.

**Comment by alaskamike** [comment]
Please add the changes to your repo - I found it through a google search, so it is probably more discoverable than mine is.

**Comment by nmalkin** [comment]
Done in #2. (I made some minor modifications, hope you don't mind.) Thanks again for making this package better!
