### ISSUE TITLE
Added ability to save figure

### ISSUE THREAD

**Issue by alaskamike** [nmalkin/plot-likert#10]
I added the following change at line 211 (in the plot_likert function.  It now returns a matplotlib plot that can then be saved as an image.  Without this, the return is a NoneType which I could not save as an image.

The new code is:
```

    lplot = plot_counts(counts, plot_scale, plot_percentage, colors, figsize=figsize)
    return lplot
```

**Comment by nmalkin** [comment]
Yeah, totally, that should be the correct behavior.

In fact, the function signature even promises that this should already be happening:
https://github.com/nmalkin/plot-likert/blob/80d2c49cf86c343fad6d6da49cb6af8fb121bd16/plot_likert/plot_likert.py#L192
…so I'm kind of surprised MyPy didn't flag this as an error earlier.

Added in a8d092f.

Thanks for flagging this!
