### ISSUE TITLE
Plot percentages from groups with different numbers of responses

### ISSUE THREAD

**Issue by JonasSchwenke** [nmalkin/plot-likert#14]
yo waddup

**Comment by nmalkin** [comment]
👋 😄 

Looks like you figured it out, but I do think the original issue was legitimate: the warning you got was kind of terse and not very clear. I tried to improve it in fecbdbc.

Here's the new text; it's long, but hopefully it's a little bit clearer:

> In your data, not all questions have the same number of responses. i.e., different numbers of people answered each question. Therefore, the percentages aren't directly comparable: X% for one question represents a different number of responses than X% for another question, yet they will appear the same in the percentage graph. This may be misleading to your reader.
