### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by Novak3** [nmalkin/plot-likert#29]
Is there a way to change the whitespace or separation between the various Likert bars?
Sometimes you've got a great big stack of bars and the whitespace eats up a lot of your page. 

I tried changing the location of the Yticks, but that only changed the location of the labels.

**Comment by nmalkin** [comment]
You should be able to do it by using a combination of the `width` and (optionally) the `figsize` parameters:
 
<img width="602" alt="Screen Shot 2022-03-16 at 22 43 34" src="https://user-images.githubusercontent.com/903179/158744806-ba7187d8-de88-4603-84a0-e36b335ab460.png">
`

**Comment by Novak3** [comment]
That sure looks like it should work, but it doesn't.
Is that parameter getting passed to Pandas with kwargs?

This:
`plot_likert.plot_likert(df_likert, dilation_scale, colors=new_palette, figsize=(15,5), width = 1)`

produces this:
`plot_likert() got an unexpected keyword argument 'width'`

(The position of the argument doesn't seem to matter.)

**Comment by nmalkin** [comment]
Yes, sorry about that, the feature I was using hasn't been released to the main/stable version of the library on PyPI.

I'm hoping to fix that soon, but for now, you can get the pre-release with `pip install --pre plot-likert`.

**Comment by Novak3** [comment]
That works-- thanks much!

**Comment by nmalkin** [comment]
[v0.4.0 is now out](https://github.com/nmalkin/plot-likert/releases/tag/v0.4.0), so this no longer requires installing the prerelease version.
