### ISSUE TITLE
Legend in x axis

### ISSUE THREAD

**Issue by antonioalmeida** [nmalkin/plot-likert#3]
Hey, great package you've got here.

However, I can't get `likert_counts` to show the number of responses in the x axis.

Following the example notebook I can get both counts and percentages, but only the percentages plot version shows the x axis legend.

```python
import plot_likert as pl

# (...) prepare data 

counts = pl.likert_counts(df, pl.scales.scores6) # this works
percentages = pl.likert_percentages(df, pl.scales.scores6) # this also works
 
# output 1
pl.plot_counts(counts, pl.scales.scores6, colors=pl.colors.likert6) # doesn't show the axis

#output 2
pl.plot_counts(percentages, pl.scales.scores6, colors=pl.colors.likert6) # works (not really showing counts, rather percentages)
```

#### Output 1
![image](https://user-images.githubusercontent.com/4543448/86156468-e8982a00-bafd-11ea-8358-159cde9e71b7.png)
#### Output 2
![image](https://user-images.githubusercontent.com/4543448/86156473-eafa8400-bafd-11ea-93eb-ebb115555a58.png)

Any tips?

**Comment by nmalkin** [comment]
Hi, I'm glad you're finding this package useful!

The issue you experienced was a bug with how the x-axis tick marks were generated. I've pushed a fix that should hopefully make them work as expected. (There are more details in the commit message.) Let me know!

**Comment by antonioalmeida** [comment]
Perfect. You even fixed the left-pad thingy. Kudos for the timely response

![image](https://user-images.githubusercontent.com/4543448/86178965-45f1a280-bb21-11ea-910c-97f85862931c.png)

**Comment by nmalkin** [comment]
Great! Thanks for reporting the issue.
