### ISSUE TITLE
Exception when values occur only once or twice

### ISSUE THREAD

**Issue by nmalkin** [nmalkin/plot-likert#38]
### Reported in https://github.com/nmalkin/plot-likert/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **hbxbgrw7913** October  6, 2022</sup>
Hey, I am trying to plot a Dataframe in which values of the scale occur only once or twice. This always seems to run into a "ValueError: attempt to get argmax of an empty sequence". I can solve this issue by setting xtick_interval = 1. But still I don't understand the error, which would help in order to handle this error, since I am plotting more than 50 plots.

This is my DataFrame

<html><body>

Pkw | Fahrrad | ÖPNV | zu Fuß
-- | -- | -- | --
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
etwas mehr | etwas mehr | weniger | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | etwas mehr | etwas mehr | etwas mehr
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN
NaN | NaN | NaN | NaN

</body>
</html>

If you could suggest any kind of help or a better explanantion, I would be very thankful!</div>

**Comment by nmalkin** [comment]
[3ac6dad](https://github.com/nmalkin/plot-likert/commit/3ac6dad2e88a35433c726cc89d0423854fbbae55) should fix this bug.

@hbxbgrw7913, if you're able to, can you check that the fix works for you? You can install it with  
`pip install --pre plot-likert`

**Comment by hbxbgrw7913** [comment]
@nmalkin it took me a little to figure out how to install the preversion in my venv in my IDE, but I finally made it, and it seems to work. Thank you!

**Comment by nmalkin** [comment]
This fix is finally released in [v0.5.0](https://github.com/nmalkin/plot-likert/releases/tag/v0.5.0)
