### ISSUE TITLE
Problem with the rounding of the bar labels

### ISSUE THREAD

**Issue by nmalkin** [nmalkin/plot-likert#44]
### from Discussion https://github.com/nmalkin/plot-likert/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **EarlvanEick** July 20, 2023</sup>
Thank you very much for this library! 

Unfortunately I have a problem with the rounding of the bar labels. I have the following aggregated dataframe: 
	        1.0	          2.0	           3.0
Q12.1_Tri	59.53	26.51	13.95
Q12.2_Tri	61.99	24.89	13.12
Q12.3_Tri	68.84	25.58	5.58
Q12.4_Tri	45.37	18.98	35.65
Q12.5_Tri	61.40	26.98	11.63

The columns are already percentages, but the problem with the rounding of the bar labels happens with individual data and absolute figures as well.

This is my code: plot_likert.plot_counts(data2,  another_scale, compute_percentages=False, bar_labels=True);

![Download](https://github.com/nmalkin/plot-likert/assets/68033866/cd75ae49-6409-45fb-993c-224feaac290f)

As you can see, the bar labels are truncated and not rounded. The same happens if I set compute_percentages as True.

Is this a bug or is did I make a mistake?
</div>

**Comment by nmalkin** [comment]
Thanks for raising this issue! I think this is more bug than feature. :-)

It was possibly intentional, because I generally want to see round numbers in my figures. However, I agree that truncating the numbers is not the correct behavior.

I've pushed out a change (b993819) in which the numbers on the bar labels will now be displayed with full precision (according to [Python's somewhat-complicated rules](https://docs.python.org/3/library/string.html#:~:text=%27g%27-,General%20format.,-For%20a%20given)).

I think this is probably better than (correctly) rounding the numbers, but if anyone has different opinions, please chime in. I can imagine eventually adding a separate argument to actually round the label numbers.

If you're able to, please test this change by installing it via `pip install git+https://github.com/nmalkin/plot-likert.git`.

**Comment by EarlvanEick** [comment]
@nmalkin Thank you very much for your quick reply. I tried to install the updated library, but I'm not really sure whether it worked, as I'm still getting the same results as before. I'm sorry, but this is the first time I installed a module from github. 
Do I have to pay attention to anything special when importing it? I imported it with import plot_likert

**Comment by nmalkin** [comment]
I think you need to run `pip uninstall plot-likert` before running the install command, because I haven't changed the version number, so pip thinks it has the latest version already, after pulling down the version via git and comparing the version numbers.

**Comment by EarlvanEick** [comment]
Thank you! That worked! 

Now I have up to three decimal places. I would prefer to have the possibility to round to zero decimal places. Maybe there is a possiblity to do this afterwards in matlibplot?
![Download](https://github.com/nmalkin/plot-likert/assets/68033866/48579960-97d0-455c-bc61-bf668b47959f)

**Comment by nmalkin** [comment]
Hi there, thanks for your patience!

I've pushed a small change (f08789b) that will allow you to access the [`BAR_LABEL_FORMAT` variable](https://github.com/nmalkin/plot-likert/blob/f08789bda3ec961e4413562717ea298ae9f79716/plot_likert/plot_likert.py#L39-L41), which you can then set as follows to get the result you're looking for:

```python
plot_likert.__internal__.BAR_LABEL_FORMAT = "%.0f"
```

Here's a full example:

[![rounding_example](https://github.com/nmalkin/plot-likert/assets/903179/efb1202a-fa40-43ec-be0e-9539857002af)](https://gist.github.com/nmalkin/9a31437d3be18d637d0b63e54926c491)
(_[Link to notebook](https://gist.github.com/nmalkin/9a31437d3be18d637d0b63e54926c491)_)

**Comment by EarlvanEick** [comment]
Hi,

Thank you very much! This works perfect! I checked it with various variables and everything is fine! Plot-likert is very powerful and helpful for me. Thanks again for the quick update!

**Comment by nmalkin** [comment]
Excellent, glad to hear it's working!

**Comment by nmalkin** [comment]
Both the fix and the new API are now available in [v0.5.0](https://github.com/nmalkin/plot-likert/releases/tag/v0.5.0)
