### ISSUE TITLE
Padding looks rather strange on non-default matplotlib styles

### ISSUE THREAD

**Issue by SapiensAnatis** [nmalkin/plot-likert#6]
I didn't notice until I changed to a style that doesn't use a white background, but it looks like you use a bit of white padding to centrally align the bars:

![white](https://user-images.githubusercontent.com/5047192/86975314-fe49c700-c16f-11ea-9cf8-340ca04855bf.png)

This can simply be fixed by changing `"white"` on line 10 of `colors.py` to `"#00000000"` (or any other colour with zero opacity), since matplotlib thankfully supports alpha channels.

**Comment by nmalkin** [comment]
Thanks, this is great! I didn't realize matplotlib supported full RGBA colors and never thought of solving it this way. (And yeah, you've discovered the magic behind the alignment. :-D)

Let me know if you'd like to make a PR (so you can be a Contributor™️  to the repo), or I can just push out the fix.

**Comment by SapiensAnatis** [comment]
I'll let you take this, it's like 10 characters so I don't see the point in a PR :)

**Comment by nmalkin** [comment]
Fair enough. :-) Done. Thanks again for the suggestion!
