### ISSUE TITLE
Error calculating xticks

### ISSUE THREAD

**Issue by alaskamike** [nmalkin/plot-likert#9]
I have a dataset with 20 questions, that I split into 2 sets to plot.  They use the same scale etc.  One set plots file, the other gives me this message.  Basically, it doesn't update the x ticks or move the legend.  Any idea what's going on?

```

>  ---------------------------------------------------------------------------
>  ValueError                                Traceback (most recent call last)
>  <ipython-input-15-10cd0e6704f9> in <module>
>        3 #print(counts)
>        4
>  ----> 5 pl.plot_counts(counts=counts2, scale=pl.scales.agree7, colors=pl.colors.likert7)
> 
>  C:\Users\AppData\Roaming\Python\Python37\site-packages\plot_likert\plot_likert.py in plot_counts(counts, scale, plot_percentage, colors, figsize, xtick_interval)
>       80         interval = xtick_interval
>       81     right_edge = max_width - center
>  ---> 82     right_labels = np.arange(0, right_edge + interval, interval)
>       83     right_values = center + right_labels
>       84     left_labels = np.arange(0, center + 1, interval)
> 
>  ValueError: Maximum allowed size exceeded

```

**Comment by nmalkin** [comment]
Hmm, that's a new one for me. Can you print out the values of the relevant variables (right_edge, interval, and maybe max_width, center)? My best guess is that somehow the interval value is set to be too big (or the right_edge is too small), but I'm not sure why that would happen.

**Comment by alaskamike** [comment]
[dataframes.zip](https://github.com/nmalkin/plot-likert/files/5640213/dataframes.zip)
Here are the two dataframes.  Maybe you can generate the same error?

**Comment by nmalkin** [comment]
Thanks for providing the data! I wasn't able to reproduce your error, everything seemed to work okay:
![pivot_1](https://user-images.githubusercontent.com/903179/101115009-74275280-3597-11eb-8d59-48f0b23e69ed.png) 
![pivot_2](https://user-images.githubusercontent.com/903179/101114962-5e199200-3597-11eb-8cc9-4f691b1dda22.png)

If it helps, here are the versions of numpy and pandas I'm running:
```
numpy               1.19.4
pandas              1.1.4
```

**Comment by alaskamike** [comment]
I think the issue is where the interval = 0.  I added the following:

```
    if interval == 0:
        interval = 1
```

at line 81, just before:

`    right_edge = max_width - center`

and the problem went away.

**Comment by nmalkin** [comment]
Yeah, a zero interval is no good. I added 80d2c49 to hopefully catch that in the future.
